language: rust
rust:
  - stable
before_install:
  - sudo apt-get -qq update
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=diff
  - cargo build
  - cargo test
