[package]
name = "rtow"
description = "Implementation of the Ray Tracing in One Weekend project"
version = "0.1.0"
authors = ["Sergiu Puscas <srg.pscs@gmail.com>"]
license = "MIT"

[dependencies]
clippy = { version = "*", optional = true }
clap = { version = "*", features = ["yaml"]}
chan = "0.1.21"
image = "0.18.0"
nalgebra = "0.14.1"
pbr = "*"
rand = "*"
regex = "*"

